sql.host=stack-overflow.cfse9bqqndon.us-east-1.rds.amazonaws.com
sql.port=3306
sql.db.name=CraterDBS
sql.db.username=craterdbuser
sql.db.password=ptschool2023

mulesoft.dev.insert=INSERT INTO mulesoft_dev(MESSAGE_ID,API_REQUEST,TASK_NAME,STATUS,REQUEST_TIMESTAMP) VALUES (:messageId,:apiRequest,:taskName,:status,:requestTimestamp)


#SFTP Server Credentials:
sfdc.userName=tmk8141-ymhb@force.com
sfdc.password=Boatmk@1999
sfdc.security.token=vHSS6DfK54rPyaM2Ak8H48OAW

