sql.host=sql5.freesqldatabase.com
sql.port=3306
sql.db.name=sql5766315
sql.db.username=sql5766315
sql.db.password=LyFif2LU6D

mulesoft.dev.insert=INSERT INTO mulesoft_dev(MESSAGE_ID,API_REQUEST,TASK_NAME,STATUS,REQUEST_TIMESTAMP) VALUES (:messageId,:apiRequest,:taskName,:status,:requestTimestamp)


#SFTP Server Credentials:
sfdc.userName=tmk8141-ymhb@force.com
sfdc.password=Boatmk@1999
sfdc.security.token=vHSS6DfK54rPyaM2Ak8H48OAW

