#%RAML 1.0
title: account-manage-api
version: v1
description: Account Manage API
protocols: [HTTP, HTTPS]

/accounts:  
  post:    
    description: Create User Account.
    body:
      application/json:
        example: !include examples/create-account-request-example.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/create-account-success-response-example.json    
      400:
        body:
          application/json:
            example: !include examples/create-account-error-response-example.json 